### ISSUE TITLE
getting issue while git clone repo

### ISSUE THREAD

**Issue by warriorwizard** [Lancelot03/Hacktoberfest-2022#94]
![image](https://user-images.githubusercontent.com/73724518/195654956-12aadac0-970b-479e-8724-2d79718294bf.png)

@Lancelot03 change the name of '1 to n--->xor.py' file i'm getting error while copying 
please fix this issue by either deleting ro renaming the file

**Comment by Lancelot03** [comment]
thanks for mentioning I rectified it.
