### ISSUE TITLE
few more file name are causing error

### ISSUE THREAD

**Issue by warriorwizard** [Lancelot03/Hacktoberfest-2022#95]
![image](https://user-images.githubusercontent.com/73724518/195657633-175eef40-83d9-4d38-be44-7977a6473a6d.png)
![image](https://user-images.githubusercontent.com/73724518/195657655-4f325385-6259-4bb4-9131-3dec7e90b826.png)
![image](https://user-images.githubusercontent.com/73724518/195657729-81737d52-defb-4351-97d6-2084efe4fad5.png)

**Comment by Lancelot03** [comment]
fixed
